id: '17150023953630.11869397994507325'
kind: workflow
name: handleSearchN
nameConfigured: true
steps:
  - id: '17150024178980.2506131885776184'
    type: executeAction
    name: execute
    params:
      - type: action
        value: '17150021661410.7898794768778816'
        valueType: custom
      - type: isActionsLibraryCall
        value: false
        valueType: custom
      - type: customParams
        value: ./execute-customParams.js
        valueType: interpolatedValue
        interpolationType: code
      - type: successMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: failureMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: mapperEnabled
        value: false
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: true
mode: manual
modeConfigured: true
parentPageId: '1'
config:
  shouldConfirm: false
  confirmMessage: Are you sure you'd like to proceed with "{{actions.handleSearchN.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.handleSearchN.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: true
  errorToast: Action "{{actions.handleSearchN.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
selected: true
configured: true
parentId: '17150653298740.9875262902613822'
